// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABGYatJz2-5E0Ev284nxR18MIsaEEYbto',
    appId: '1:1007373981300:web:2f40fe698a397035846321',
    messagingSenderId: '1007373981300',
    projectId: 'fir-flutter-codelab-63ba3',
    authDomain: 'fir-flutter-codelab-63ba3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-63ba3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJgh0Fw0Zm7eqk61UeeIaZgf8F30gNFw',
    appId: '1:1007373981300:android:fa92e2e331887a25846321',
    messagingSenderId: '1007373981300',
    projectId: 'fir-flutter-codelab-63ba3',
    storageBucket: 'fir-flutter-codelab-63ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCXU4ACZwVhIU1hLzNsChYhvNR-BhF3cs',
    appId: '1:1007373981300:ios:2e29124d907021ca846321',
    messagingSenderId: '1007373981300',
    projectId: 'fir-flutter-codelab-63ba3',
    storageBucket: 'fir-flutter-codelab-63ba3.appspot.com',
    iosClientId: '1007373981300-n5t0eablv1liooc77s9po33lclrcnmb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCXU4ACZwVhIU1hLzNsChYhvNR-BhF3cs',
    appId: '1:1007373981300:ios:2e29124d907021ca846321',
    messagingSenderId: '1007373981300',
    projectId: 'fir-flutter-codelab-63ba3',
    storageBucket: 'fir-flutter-codelab-63ba3.appspot.com',
    iosClientId: '1007373981300-n5t0eablv1liooc77s9po33lclrcnmb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
